"""Pull request title and description, built from what the agents recorded."""

from __future__ import annotations

from typing import Any

from devassist_common.db import Job, Patch

TITLE_LIMIT = 72


def pull_request_title(task: str) -> str:
    first = task.strip().splitlines()[0] if task.strip() else "DevAssist change"
    if len(first) > TITLE_LIMIT:
        first = first[: TITLE_LIMIT - 1].rstrip() + "…"
    return first


def _bullets(items: list[Any]) -> list[str]:
    return [f"- {item}" for item in items if item]


def _check_line(name: str, check: dict[str, Any] | None) -> str:
    if not check:
        return f"| {name} | n/a | |"
    detail = check.get("summary") or ""
    return f"| {name} | {check.get('status', 'n/a')} | {detail} |"


def pull_request_body(job: Job, patch: Patch) -> str:
    plan = job.plan or {}
    review = job.review or {}
    lines = ["## Task", "", job.task.strip(), ""]

    if plan.get("summary"):
        lines += ["## Plan", "", plan["summary"], ""]
        lines += _bullets(plan.get("steps") or [])
        lines.append("")

    if review:
        lines += ["## Review", "", review.get("summary", ""), ""]
        lines.append(f"**Risk:** {review.get('risk_level', 'unknown')}")
        concerns = _bullets(review.get("concerns") or [])
        if concerns:
            lines += ["", "**Check before merging:**", *concerns]
        lines.append("")

    runs = sorted(patch.validation_runs, key=lambda r: r.created_at)
    if runs:
        run = runs[-1]
        lines += [
            "## Sandbox validation",
            "",
            "| Check | Status | Summary |",
            "| --- | --- | --- |",
            _check_line("Tests", run.tests),
            _check_line("Security", run.security),
            _check_line("Static analysis", run.static_analysis),
            "",
        ]

    lines += [
        "---",
        f"Generated by DevAssist in {patch.iteration} iteration(s) "
        f"({patch.files_changed} files, +{patch.additions}/-{patch.deletions}); "
        f"model cost ${job.total_cost_usd:.4f}. Job `{job.id}`.",
    ]
    return "\n".join(lines)
