#!/usr/bin/env bash
# Publish each directory in sample-repos/ as a bare git repository under
# .data/sample-repos/<name>.git, so services can clone it like any remote
# (file:///sample-repos/<name>.git inside the containers).
#
# Commits use a fixed author and date, so the commit SHA is reproducible:
# re-running this script without changes is a no-op for the indexer.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.data/sample-repos"
mkdir -p "$OUT"

export GIT_AUTHOR_NAME="DevAssist Samples" GIT_AUTHOR_EMAIL="samples@devassist.local"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
export GIT_AUTHOR_DATE="2026-01-01T00:00:00Z" GIT_COMMITTER_DATE="2026-01-01T00:00:00Z"

# Containers run as a different uid than the owner of these files, which git
# refuses by default ("dubious ownership"). Services mount this file as their
# global git config; it trusts exactly the sample repos and nothing else.
GITCONFIG="$OUT/gitconfig"
echo "# Generated by scripts/publish-sample-repos.sh" > "$GITCONFIG"

for src in "$ROOT"/sample-repos/*/; do
  name="$(basename "$src")"
  bare="$OUT/$name.git"
  work="$(mktemp -d)"
  trap 'rm -rf "$work"' EXIT

  cp -R "$src". "$work"/
  # Never publish local build/test byproducts.
  find "$work" \( -name __pycache__ -o -name .pytest_cache -o -name node_modules -o -name '*.pyc' \) -prune -exec rm -rf {} +
  git -C "$work" init --quiet -b main
  git -C "$work" add -A
  git -C "$work" commit --quiet -m "Initial import of $name sample"

  rm -rf "$bare"
  git clone --quiet --bare "$work" "$bare"
  # Containers run as a different uid than the files' owner.
  chmod -R a+rX "$bare"
  printf '[safe]\n\tdirectory = /sample-repos/%s.git\n' "$name" >> "$GITCONFIG"
  echo "published $name -> file:///sample-repos/$name.git ($(git -C "$bare" rev-parse --short HEAD))"
  rm -rf "$work"
  trap - EXIT
done
chmod a+r "$GITCONFIG"
